/***
Static Variable Class
Usage : Replace hardcoded values
***/

public virtual class staticVariableClass {

    // String Variables
    public static String Issue_Status_Value_Low {get {return 'Low';} }
    public static String Issue_Status_Value_Medium {get {return 'Medium';} }
    public static String Issue_Status_Value_High {get {return 'High';} }
    public static String Date_Format {get {return 'yyyy-MM-dd';} }
    public static String Record_Type_Business_Task {get {return 'Business Task';} }
    public static String Record_Type_Task_Read_Only {get {return 'Task Read Only';} }
    public static String Record_Type_Business_Task_Editable {get {return 'Business Task Editable';} }
    public static String Record_Type_Editable_Task {get {return 'Editable Task';} }
    public static String Task_Status_Value_Active {get {return 'Active';} }
    public static String Task_Status_Value_Open {get {return 'Open';} }
    public static String Task_Status_Value_Completed {get {return 'Completed';} }
    public static String String_Team_Name_Value_Account_Manager {get {return 'Account Manager';} }
    public static String String_Team_Name_Value_E2E_PM {get {return 'E2E PM';} }
    public static String String_Value_Underscore {get {return '_';} }
    public static String String_Standard_User {get {return 'Standard User';} }
    public static String String_Value_Id {get {return 'id';} }
    public static String Task_Status_Value_Amber {get {return 'Amber';} }
    public static String Task_RAG_Status_Value_Red {get {return 'Red';} }
    public static String Task_RAG_Status_Value_Green {get {return 'Green';} }
    public static String String_Status {get {return 'Completed';} }
    public static String String_Semicolon {get {return ';';} }
    public static String String_Failure {get {return 'Failure';} }
    public static String String_Success {get {return 'Successful';} }
    
    
    // Error Message 
    public static String String_Value_Enter_Issue_Name {get {return 'Please enter Issue Name ';} }
    public static String String_Value_Enter_Description {get {return 'Please enter Description';} }
    
    // Special Characters
    public static String String_Value_Slash {get {return '/';} }
    public static String String_Value_Hyphen {get {return '-';} }
    
    // Integer Variables
    public static Integer Counter_Value_Zero {get {return 0;} }
    public static Integer Counter_Value_Three {get {return 3;} }
    public static Integer Counter_Value_Ten {get {return 10;} }
    
    public static Integer Counter_Value_Ten1 {get {return 10;} }
    public static Integer Counter_Value_Ten2 {get {return 20;} }
    public static Integer Counter_Value_Ten3 {get {return 30;} }
    public static Integer Counter_Value_Ten4 {get {return 40;} }
    public static Integer Counter_Value_Ten5 {get {return 50;} }
    //end here 
}
